Renée firepower restapi101 md2
CiscoDevNet/fmc-rest-api pull request #27
Opened 2018-05-29 17:10 UTC by ReneeBornstein

2018-05-29 17:18 UTC, annegentle requested changes
Looking really good! Much improved. Minor notes inline.

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
> +You can play live with API explorer on the FMC REST API sandbox:
API explorer should be API Explorer to be consistent with the rest of the file, looks like 👓

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
> +FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to
token-based

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
> +FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to
Api explorer -> API Explorer

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
> +https://learninglabs.cisco.com/lab/firepower-restapi-102/step/1
Probably just use Markdown link here, `You can learn more in the [Firepower REST API 102 lab](https://learninglabs.cisco.com/lab/firepower-restapi-102/step/1).`

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
> +http://www.cisco.com/c/en/us/td/docs/security/firepower/610/configuration/guide/fpmc-config-guide-v61/logging_into_firepower_system.html
Probably just use a Markdown link here rather than show the long URL.

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
>  http://www.cisco.com/c/en/us/td/docs/security/firepower/610/configuration/guide/fpmc-config-guide-v61/logging_into_firepower_system.html
Probably just use a Markdown link here rather than show the long URL.

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-101/2.md
> +*  Log in with your username and password and click **Sign In**.
devnet -> DevNet -- not sure we use the term "live" sandbox, I've not seen that. Maybe Always-On Sandbox?

2018-05-29 17:18 UTC, annegentle commented on labs/firepower-restapi-103/1.md
> +- reg_key is an unique alphanumeric registration key required to register a device to the FMC.
These can probably be literals: `reg_key` and `nat_id`.

2018-05-29 17:48 UTC, ReneeBornstein commented
Thanks. I know you’re trying to get stuff done so you can leave on vacation, but could you answer what I asked on Spark before you’re gone? It’s about Atom, and Paul knows nothing about that. Thanks ever so!

From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Tuesday, May 29, 2018 at 10:18 AM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] Renée firepower restapi101 md2 (#27)


@annegentle requested changes on this pull request.

Looking really good! Much improved. Minor notes inline.

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191503951>:

>

-You can play live with API explorer on the FMC REST API sandbox

+You can play live with API explorer on the FMC REST API sandbox:

API explorer should be API Explorer to be consistent with the rest of the file, looks like 👓

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191504068>:

>

-FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to “X-auth-access-token” and “value” containing a valid access token . Api explorer also follows this, but it is automated by Explorer UI. You can learn more in firepower-restapi-102 lab.

+FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to “X-auth-access-token” and “value” containing a valid access token. Api explorer also follows this, but it is automated by Explorer UI. You can learn more in firepower-restapi-102 lab:

token-based

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191504178>:

>

-FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to “X-auth-access-token” and “value” containing a valid access token . Api explorer also follows this, but it is automated by Explorer UI. You can learn more in firepower-restapi-102 lab.

+FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to “X-auth-access-token” and “value” containing a valid access token. Api explorer also follows this, but it is automated by Explorer UI. You can learn more in firepower-restapi-102 lab:

Api explorer -> API Explorer

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191504450>:

>

-FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to “X-auth-access-token” and “value” containing a valid access token . Api explorer also follows this, but it is automated by Explorer UI. You can learn more in firepower-restapi-102 lab.

+FMC REST API uses token based authentication. To invoke a REST call on FMC, you need to use a valid access token. On every REST call to access resource URLs you need to add a header with "key" set to “X-auth-access-token” and “value” containing a valid access token. Api explorer also follows this, but it is automated by Explorer UI. You can learn more in firepower-restapi-102 lab:

+https://learninglabs.cisco.com/lab/firepower-restapi-102/step/1

Probably just use Markdown link here, You can learn more in the [Firepower REST API 102 lab](https://learninglabs.cisco.com/lab/firepower-restapi-102/step/1).

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191504590>:

>  ## Authentication to the API Explorer

 The REST API relies on the same authentication as the FMC UI. Each function in the REST API maps to permissions in the FMC.



-You can log into the API Explorer using any account on the FMC, but you will only be able to perform the functions for which the account has permissions. For more information on setting permissions for user roles, see the FMC Configuration Guide.

+You can log into the API Explorer using any account on the FMC, but you will only be able to perform the functions for which the account has permissions. For more information on setting permissions for user roles, see the FMC Configuration Guide:

+http://www.cisco.com/c/en/us/td/docs/security/firepower/610/configuration/guide/fpmc-config-guide-v61/logging_into_firepower_system.html

Probably just use a Markdown link here rather than show the long URL.

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191504607>:

>

 ## Logging into API Explorer

-The REST API uses the same authentication and permission model as the Firepower Management Center. See the Firepower Management Center Configuration Guide for more information.

+The REST API uses the same authentication and permission model as the Firepower Management Center. See the FMC Configuration Guide for more information.

 http://www.cisco.com/c/en/us/td/docs/security/firepower/610/configuration/guide/fpmc-config-guide-v61/logging_into_firepower_system.html

Probably just use a Markdown link here rather than show the long URL.

________________________________

In labs/firepower-restapi-101/2.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191504795>:

>

-## Logging Procedure

-*  Navigate to the following URL: https://management_center_IP_or_name/api/api-explorer or try devnet live sandbox https://fmcrestapisandbox.cisco.com/api/api-explorer/

-*  Log in with your username and password and click **Sign In**

+## Logging procedure

+*  Navigate to the following URL: https://management_center_IP_or_name/api/api-explorer or try https://fmcrestapisandbox.cisco.com/api/api-explorer/ (the devnet live sandbox).

+*  Log in with your username and password and click **Sign In**.

devnet -> DevNet -- not sure we use the term "live" sandbox, I've not seen that. Maybe Always-On Sandbox?

________________________________

In labs/firepower-restapi-103/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#discussion_r191505238>:

>

   The command has the following syntax:

 ```shell

   $configure manager add <hostname | IPv4_address | IPv6_address | DONTRESOLVE> reg_key <nat_id>

 ```

-In the above syntax,

-`<hostname | IPv4_address | IPv6_address | DONTRESOLVE> ` specifies either the fully qualified host name or IP address of the Firepower Management Center. If the Firepower Management Center is not directly addressable, use DONTRESOLVE.

-reg_key is an unique alphanumeric registration key required to register a device to the Firepower Management Center.

-nat_id is an optional alphanumeric string used during the registration process between the Firepower Management Center and the device. It is required if the hostname is set to DONTRESOLVE.

+In the above syntax:

+- `<hostname | IPv4_address | IPv6_address | DONTRESOLVE> ` specifies either the fully qualified host name or IP address of the FMC. If the FMC is not directly addressable, use DONTRESOLVE.

+- reg_key is an unique alphanumeric registration key required to register a device to the FMC.

These can probably be literals: reg_key and nat_id.

—
You are receiving this because you authored the thread.
Reply to this email directl [...]

2018-05-29 23:26 UTC, annegentle requested changes
Looks good, not all requests addressed but I do see incremental changes in this set.

2018-05-29 23:26 UTC, annegentle commented on labs/firepower-restapi-101/2.md
Good, I do see the requested change to the URL, now also look for an extra space after token and before the period for the third-to-last sentence, plus Api Explorer should be API Explorer.

2018-05-29 23:26 UTC, annegentle commented on labs/firepower-restapi-103/1.md
> +## Lab objective
I think I've mostly seen "Objectives" or "Objective" for this heading - adding Lab is probably not consistent.

2018-05-29 23:50 UTC, annegentle approved these changes
Looks good -only remaining question is if we want to use Objectives instead of Lab objectives?

2018-05-30 00:59 UTC, paulzim commented
Yeah, I think “Lab Objectives” is kind of redundant… they already know they’re in the lab. +1 for Lab objectives

From: Anne Gentle <notifications@github.com>
Sent: Tuesday, May 29, 2018 4:50 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: Paul Zimmerman (pzimmerm) <pzimmerm@cisco.com>; Review requested <review_requested@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] Renée firepower restapi101 md2 (#27)


@annegentle approved this pull request.

Looks good -only remaining question is if we want to use Objectives instead of Lab objectives?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/27#pullrequestreview-124211150>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AATew6ibsbNl3XYTHnX6TFH6VpfHCaT8ks5t3d6ygaJpZM4UR4x6>.

2018-06-05 21:40 UTC, annegentle approved these changes

2018-06-05 21:41 UTC, annegentle commented
I'll resolve conflicts in `.DS_Store` on this PR and get it merged. Thanks!

2018-06-05 21:54 UTC, merged