CLUS editing
CiscoDevNet/fmc-rest-api pull request #29
Opened 2018-05-30 14:45 UTC by ReneeBornstein

* commas and periods

2018-06-01 23:03 UTC, paulzim requested changes
Some minor nits

2018-06-01 23:03 UTC, paulzim commented on labs/firepower-restapi-101/1.md
>  ## Learning Objective
This should be "Objectives", so delete the "Learning" and add an "s"

2018-06-01 23:03 UTC, paulzim commented on labs/firepower-restapi-101/1.md
> +if you are using DevNet sandbox  https://fmcrestapisandbox.cisco.com/api/api-explorer/, REST API is already enabled by the administrator.
Sentences should start with a capital

2018-06-05 22:01 UTC, annegentle approved these changes

2018-06-05 22:01 UTC, merged