CLUS-firepower-restapi-104-md1
CiscoDevNet/fmc-rest-api pull request #30
Opened 2018-05-30 22:02 UTC by ReneeBornstein

* changed words to acronyms
* changed bullet sentences structure

2018-06-01 23:39 UTC, paulzim requested changes
Good stuff, just a couple of minor updates

2018-06-01 23:39 UTC, paulzim commented on labs/firepower-restapi-104/1.md
> +It's best if you know the basic understanding of REST principles.
I liked the original better (adding the period of course)

2018-06-01 23:39 UTC, paulzim commented on labs/firepower-restapi-104/1.md
> +## Learning objective
I think this is just supposed to be "Objectives", so ditch the "Learning"

2018-06-05 21:37 UTC, annegentle approved these changes

2018-06-05 21:37 UTC, merged