CLUS-firepower-restapit106-md1
CiscoDevNet/fmc-rest-api pull request #34
Opened 2018-05-30 23:37 UTC by ReneeBornstein

* lenghtened sentence space
* added words to make whole
   sentences.

2018-06-06 16:22 UTC, paulzim requested changes

2018-06-06 16:22 UTC, paulzim commented on labs/firepower-restapi-106/1.md
> +## Lab objective
Should just be "Objectives"

2018-06-06 16:22 UTC, paulzim commented on labs/firepower-restapi-106/1.md
> +It's best if you have a basic understanding of REST principles, Firewalls, and FMC REST API.
The original is better... "It's best..." is a judgement statement

2018-06-22 22:23 UTC, annegentle requested changes
Couple of notes inline.

2018-06-22 22:23 UTC, annegentle commented on labs/firepower-restapi-106/1.md
> +## Learning objective
This section "Learning objective" is redundant and can be removed.

2018-06-22 22:23 UTC, annegentle commented on labs/firepower-restapi-106/1.md
> +Object overrides allow you to define device-specific or domain-specific values for certain types of object, including network, port, VLAN tag, and URL.
"...certain types of objects," Seems like it should be plural objects.

2018-06-22 22:23 UTC, annegentle commented on labs/firepower-restapi-106/1.md
> +***For example:*** <mark> You might want to deny ICMP traffic to the different departments in your company, each of which is connected to a different network. You can do this by defining an access co
I'm not sure what the `<mark>` tags do here? Does it do something in the output?

2018-06-24 22:42 UTC, ReneeBornstein commented
OMG, another weird error. I opened the GitHub doc link you sent, clicked on Files changed, and copied that to another window, so I could edit it. Usually I then just click on the pencil icon to edit the file. But this time I got this error:

[cid:image001.png@01D40BD1.FE73A850]

I’ve never had that happen before. I am logged in, so I guess somehow my push access (whatever that is) suddenly isn’t working?

From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Friday, June 22, 2018 at 3:23 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] CLUS-firepower-restapit106-md1 (#34)


@annegentle requested changes on this pull request.

Couple of notes inline.

________________________________

In labs/firepower-restapi-106/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/34#discussion_r197582593>:

>

-## Learning Objective

-You will learn how to do operations (GET, POST) using Firepower management center (FMC) objects to configure NGFW and other Firepower devices.

+

+## Learning objective

This section "Learning objective" is redundant and can be removed.

________________________________

In labs/firepower-restapi-106/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/34#discussion_r197582747>:

>  or rename the zones/groups.* </mark>



 Object names must be unique within the domain hierarchy. The system may identify a conflict with the name

 of an object you cannot view in your current domain. For objects that support grouping, you can group objects in the current domain with objects inherited from ancestor domains.



-Object overrides allow you to define device-specific or domain-specific values for certain types of object,

-including network, port, VLAN tag, and URL.

+Object overrides allow you to define device-specific or domain-specific values for certain types of object, including network, port, VLAN tag, and URL.

"...certain types of objects," Seems like it should be plural objects.

________________________________

In labs/firepower-restapi-106/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/34#discussion_r197582952>:

> -

-You can create an object whose definition works for most devices, and then use overrides to specify

-modifications to the object for the few devices that need different definitions. You can also create an object

-that needs to be overridden for all devices, but its use allows you to create a single policy for all devices.

-Object overrides allow you to create a smaller set of shared policies for use across devices without giving up

-the ability to alter policies when needed for individual devices.

-

-***For example:*** <mark> you might want to deny ICMP traffic to the different departments in your company, each of

-which is connected to a different network. You can do this by defining an access control policy with a rule

-that includes a network object called Departmental Network. By allowing overrides for this object, you can

-then create overrides on each relevant device that specifies the actual network where that device is connected. </mark>

+An object override allows you to define an alternate value for an object, which the system uses for the devices you specify.

+

+You can create an object whose definition works for most devices, and then use overrides to specify modifications to the object for the few devices that need different definitions. You can also create an object that needs to be overridden for all devices, but its use allows you to create a single policy for all devices. Object overrides allow you to create a smaller set of shared policies for use across devices, without giving up the ability to alter policies when needed for individual devices.

+

+***For example:*** <mark> You might want to deny ICMP traffic to the different departments in your company, each of which is connected to a different network. You can do this by defining an access control policy with a rule that includes a network object called Departmental Network. By allowing overrides for this object, you can then create overrides on each relevant device that specifies the actual network where that device is connected. </mark>

I'm not sure what the <mark> tags do here? Does it do something in the output?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/34#pullrequestreview-131362833>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlQdkIi43-WrtgjLzFGxqoRf2ZRAZ5Hfks5t_W52gaJpZM4UUK8w>.

2018-06-26 16:47 UTC, ReneeBornstein reviewed
Testing to see if I can edit after making this comment.

2018-06-29 16:48 UTC, annegentle approved these changes

2018-06-29 16:48 UTC, merged