CLUS-firepower-restapi107-md1
CiscoDevNet/fmc-rest-api pull request #36
Opened 2018-05-31 00:08 UTC by ReneeBornstein

* removed capitals
* added parts of sentences
* lengthened sentence spacing

2018-06-06 16:25 UTC, paulzim requested changes

2018-06-06 16:25 UTC, paulzim commented on labs/firepower-restapi-107/1.md
> +## Lab objective
Should be "Objectives"

2018-06-06 16:25 UTC, paulzim commented on labs/firepower-restapi-107/1.md
> + It's best if you have a basic understanding of REST principles, Firewalls, FMC REST API.
The original is better. "It's best..." is a judgement call.

2018-06-22 22:24 UTC, annegentle requested changes
Still need to address review comments here.

2018-07-10 21:46 UTC, annegentle approved these changes

2018-07-10 21:46 UTC, merged