CLUS-firepower-restapi109-md1
CiscoDevNet/fmc-rest-api pull request #39
Opened 2018-05-31 15:06 UTC by ReneeBornstein

* removed capitals from headings
* added parts of sentences
* changed a long sentence to a bullet
   list
* added commas and colons

2018-06-06 19:09 UTC, annegentle requested changes

2018-06-06 19:09 UTC, annegentle commented on labs/firepower-restapi-109/1.md
> +## Lab objective
The Lab and Learning Objective sections can be combined into ## Objectives.

2018-06-06 19:09 UTC, annegentle commented on labs/firepower-restapi-109/1.md
> +*Look for ID( "id" )* in the response window of API explorer:
I think it was API Explorer previously.

2018-06-22 22:25 UTC, annegentle approved these changes

2018-06-22 22:25 UTC, annegentle commented
I'll merge this now but will still need the /post/files/ references cleaned up.

2018-06-22 22:25 UTC, merged

2018-06-24 22:33 UTC, ReneeBornstein commented
Sorry, what does /post/files mean?

From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Friday, June 22, 2018 at 3:25 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] CLUS-firepower-restapi109-md1 (#39)


I'll merge this now but will still need the /post/files/ references cleaned up.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/39#issuecomment-399599141>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlQdkCdVm6ocXBz9LsFXC4guf3cipxHjks5t_W7ogaJpZM4UVN3Y>.