CLUS-firepower-restapi110-md1
CiscoDevNet/fmc-rest-api pull request #43
Opened 2018-05-31 15:44 UTC by ReneeBornstein

* changed sentence strutures
* moved links to earlier parts of
  sentence to avoid periods
* lengthened sentence spacing

2018-06-06 16:32 UTC, paulzim requested changes
Just a minor fix

2018-06-06 16:32 UTC, paulzim commented on labs/firepower-restapi-110/1.md
> +## Lab objective
Should just be "Objectives"

2018-06-22 22:27 UTC, annegentle requested changes
Some comments inline.

2018-06-22 22:27 UTC, annegentle commented on labs/firepower-restapi-110/1.md
> +## Learning objective
Can eliminate the "Learning objective" heading here.

2018-06-22 22:27 UTC, annegentle commented on labs/firepower-restapi-110/1.md
> +  * Click the download file icon () next to the client hostname to download the certificate file. Copy it to the system on which you plan to run the eStreamer client.
There are a couple of empty parens `()` here and below, should those simply be deleted?

2018-06-22 22:27 UTC, annegentle commented on labs/firepower-restapi-110/1.md
> +* From <https://developer.cisco.com/site/firepower/docs/downloads/estreamer-api/> download the version of the eStreamer SDK which matches the version of your FMC.
Use Markdown for the link.

2018-06-24 22:46 UTC, ReneeBornstein commented
This one same as last email you sent:

OMG, another weird error. I opened the GitHub doc link you sent, clicked on Files changed, and copied that to another window, so I could edit it. Usually I then just click on the pencil icon to edit the file. But this time I got this error:

[/var/folders/9x/dk6rpbtd6tnc0tqvtk73lz100000gn/T/com.microsoft.Outlook/WebArchiveCopyPasteTempFiles/cidimage001.png@01D40BD1.FE73A850]

I’ve never had that happen before. I am logged in, so I guess somehow my push access (whatever that is) suddenly isn’t working?


From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Friday, June 22, 2018 at 3:27 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] CLUS-firepower-restapi110-md1 (#43)


@annegentle requested changes on this pull request.

Some comments inline.

________________________________

In labs/firepower-restapi-110/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/43#discussion_r197583295>:

>

 ## Prerequisites

-Basic understanding of Firepower Solutions and Firepower threat technologies

+It's best if you already have basic understanding of Firepower Solutions and Firepower threat technologies.

+

+## Learning objective

Can eliminate the "Learning objective" heading here.

________________________________

In labs/firepower-restapi-110/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/43#discussion_r197583395>:

>

-  * Click the download file icon () next to the client hostname to download the

-    certificate file and copy it to the system on which you plan to run the

-    eStreamer client.

+  * Click the download file icon () next to the client hostname to download the certificate file. Copy it to the system on which you plan to run the eStreamer client.

There are a couple of empty parens () here and below, should those simply be deleted?

________________________________

In labs/firepower-restapi-110/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/43#discussion_r197583418>:

>

     `Note: In a multi domain deployment, you can create an eStreamer client in any domain. The authentication certificate allows the client to request events only from the client certificate's domain and any descendant domains. The eStreamer configuration page shows only clients associated with the current domain, so if you want to download or revoke a certificate, switch to the domain where the client was created.`



-* Download the version of the eStreamer SDK which matches the version of your FMC from <https://developer.cisco.com/site/firepower/docs/downloads/estreamer-api/>

+* From <https://developer.cisco.com/site/firepower/docs/downloads/estreamer-api/> download the version of the eStreamer SDK which matches the version of your FMC.

Use Markdown for the link.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/43#pullrequestreview-131363667>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlQdkC0WgnOE7k-8sw-z7xJFKO2ndu6kks5t_W9SgaJpZM4UVSJY>.

2018-07-10 21:51 UTC, annegentle approved these changes

2018-07-10 21:51 UTC, merged