CLUS-firepower-restapi111-md1
CiscoDevNet/fmc-rest-api pull request #44
Opened 2018-05-31 17:03 UTC by ReneeBornstein

* changed sentences
* removed capitls in headers
* removed estimated time
* added link for different lab

2018-06-06 16:34 UTC, paulzim requested changes

2018-06-06 16:34 UTC, paulzim commented on labs/firepower-restapi-111/1.md
> +## Lab objective
Should just be "Objectives"

2018-06-06 16:34 UTC, paulzim commented on labs/firepower-restapi-111/1.md
> +2. In the API CONSOLE, post the JSON below to configure a [STIX source](https://cisco.box.com/shared/static/hxlc1d1r8u3naaj876mqwucuqjuywx01.txt).
Good!

2018-06-22 22:30 UTC, annegentle requested changes

2018-06-22 22:30 UTC, annegentle commented on labs/firepower-restapi-111/1.md
> +## Learning objective
The heading, Learning objective, can be removed.

2018-06-22 22:30 UTC, annegentle commented on labs/firepower-restapi-111/1.md
> +
Calls can be lowercase here.

2018-06-22 22:30 UTC, annegentle commented on labs/firepower-restapi-111/1.md
> +### To View observables
Maybe revise as "View observables?"

2018-06-22 22:30 UTC, annegentle commented on labs/firepower-restapi-111/1.md
> +### To View incidents
Could be revised to "View incidents."

2018-06-22 22:30 UTC, annegentle commented on labs/firepower-restapi-111/1.md
> +2. Log in with your username and password and click "Sign In".
We should probably say more about how people get the credentials for the DevNet Sandbox... as I understand it, they don't want to publish the actual credentials here though... let's find someone with a definitive answer.

2018-06-24 22:47 UTC, ReneeBornstein commented
This one, too. Maybe you did something with the reviews that made it not allow me to do any changes?

OMG, another weird error. I opened the GitHub doc link you sent, clicked on Files changed, and copied that to another window, so I could edit it. Usually I then just click on the pencil icon to edit the file. But this time I got this error:

[/var/folders/9x/dk6rpbtd6tnc0tqvtk73lz100000gn/T/com.microsoft.Outlook/WebArchiveCopyPasteTempFiles/cidimage001.png@01D40BD1.FE73A850]

I’ve never had that happen before. I am logged in, so I guess somehow my push access (whatever that is) suddenly isn’t working?


From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Friday, June 22, 2018 at 3:30 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] CLUS-firepower-restapi111-md1 (#44)


@annegentle requested changes on this pull request.

________________________________

In labs/firepower-restapi-111/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/44#discussion_r197583538>:

>

 ## Prerequisites

-Basic understanding of REST principles

-Optional: Learning Lab "FMC - REST - API - 102" to get basic understanding of accessing FMC REST APIs using tokens.

+It's best if you already  have basic understanding of REST principles. Optionally, you can work through [Learning Lab "FMC - REST - API - 102](https://learninglabs.cisco.com/lab/firepower-restapi-102/step/1) before this lab, in order to get basic understanding of accessing FMC REST APIs using tokens.

+

+

+## Learning objective

The heading, Learning objective, can be removed.

________________________________

In labs/firepower-restapi-111/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/44#discussion_r197583565>:

>

 ## FMC REST API Explorer

-The API Explorer provides the list of APIs available on the Firepower Management Center (FMC), their details and the ability to make permissible Rest API Calls using a simplified API console.

+The API Explorer provides the list of APIs available on the FMC, their details, and the ability to make permissible Rest API Calls using a simplified API console.

+

Calls can be lowercase here.

________________________________

In labs/firepower-restapi-111/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/44#discussion_r197583716>:

>

-Observables represent stateful properties or measurable events pertinent to the operation of computers and networks E.g., IPs, Domains, URLs, File SHA’s etc.

+### To View observables

Maybe revise as "View observables?"

________________________________

In labs/firepower-restapi-111/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/44#discussion_r197583742>:

>



-### To View Incidents

+### To View incidents

Could be revised to "View incidents."

________________________________

In labs/firepower-restapi-111/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/44#discussion_r197583839>:

>

-2. Log in with your username and password and click "Sign In"

+2. Log in with your username and password and click "Sign In".

We should probably say more about how people get the credentials for the DevNet Sandbox... as I understand it, they don't want to publish the actual credentials here though... let's find someone with a definitive answer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/44#pullrequestreview-131363936>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlQdkJSJgWH5UOLhz_FQJOJnzYybNVHWks5t_W__gaJpZM4UVaBJ>.

2018-07-10 21:52 UTC, annegentle approved these changes

2018-07-10 21:52 UTC, merged