CLUS-firepower-restapi112-md1
CiscoDevNet/fmc-rest-api pull request #46
Opened 2018-05-31 19:33 UTC by ReneeBornstein

* changed name of lab session to
   "this".
* added to sentences.
* added commas and colons

2018-06-06 16:40 UTC, paulzim requested changes

2018-06-06 16:40 UTC, paulzim commented on labs/firepower-restapi-112/1.md
> +## Lab objective
Should just be "Objectives"

2018-06-06 16:40 UTC, paulzim commented on labs/firepower-restapi-112/1.md
> +It's best if you already have basic understanding of REST principles and firewalls.
"It's best..." is a judgement call. The original is better.

2018-06-22 22:32 UTC, annegentle requested changes
You could also delete the extra /posts/files/lab-id image references here if you want.

2018-06-22 22:32 UTC, annegentle commented on labs/firepower-restapi-112/1.md
> +## Learning objective
You can delete "Learning objective" heading.

2018-06-22 22:32 UTC, annegentle commented on labs/firepower-restapi-112/1.md
> +If you are using the [DevNet Sandbox] (https://fmcrestapisandbox.cisco.com/api/api-explorer/), for this workshop session the username and password is provided to you. These credentials are only valid
Having a space after the square bracket `]` means the link will not render correctly. I wonder also why this link is the fmcrestapisandbox, but in the prior PR the link was https://cisco-tid.cisco.com/api/api-explorer/?

2018-06-22 22:32 UTC, annegentle commented on labs/firepower-restapi-112/1.md
> +This time you need to click on the POST operation, and Click Examples to get JSON.
Click Examples probably doesn't need to be capitalized.

2018-06-22 22:32 UTC, annegentle commented on labs/firepower-restapi-112/1.md
> +Copy and paste the JSON in the API CONSOLE *Body* section, and Click POST.
Click does not need to be capitalized here.

2018-06-24 22:48 UTC, ReneeBornstein commented
Yet another one:

OMG, another weird error. I opened the GitHub doc link you sent, clicked on Files changed, and copied that to another window, so I could edit it. Usually I then just click on the pencil icon to edit the file. But this time I got this error:

[/var/folders/9x/dk6rpbtd6tnc0tqvtk73lz100000gn/T/com.microsoft.Outlook/WebArchiveCopyPasteTempFiles/cidimage001.png@01D40BD1.FE73A850]

I’ve never had that happen before. I am logged in, so I guess somehow my push access (whatever that is) suddenly isn’t working?


From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Friday, June 22, 2018 at 3:32 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] CLUS-firepower-restapi112-md1 (#46)


@annegentle requested changes on this pull request.

You could also delete the extra /posts/files/lab-id image references here if you want.

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197583893>:

>



-## Learning Objective

-After completing this module you will have a basic understanding of FMC REST APIs CRUD operations

+## Learning objective

You can delete "Learning objective" heading.

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197583993>:

>



 ## Read operation GET

-If you are using DevNet sandbox  https://fmcrestapisandbox.cisco.com/api/api-explorer/

-

-For the CLUS 17 workshop session the username and password is provided to you. These credentials are only valid for the CLUS17 session.

+If you are using the [DevNet Sandbox] (https://fmcrestapisandbox.cisco.com/api/api-explorer/), for this workshop session the username and password is provided to you. These credentials are only valid for this session.

Having a space after the square bracket ] means the link will not render correctly. I wonder also why this link is the fmcrestapisandbox, but in the prior PR the link was https://cisco-tid.cisco.com/api/api-explorer/?

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197584043>:

>  ## Write operation POST



-This time you need to click on the POST operation and Click Examples to get JSON

+This time you need to click on the POST operation, and Click Examples to get JSON.

Click Examples probably doesn't need to be capitalized.

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197584062>:

> @@ -67,7 +68,8 @@ Alternatively, You can copy JSON from here.

 ```





-Copy and paste the JSON in the API CONSOLE *Body* section and Click POST

+

+Copy and paste the JSON in the API CONSOLE *Body* section, and Click POST.

Click does not need to be capitalized here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#pullrequestreview-131364385>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlQdkKa94RZieP8tnD6UbQtSHLoIhe2uks5t_XB8gaJpZM4UVnHP>.

2018-06-25 14:18 UTC, ReneeBornstein commented
Hmmm, so with all of these do you think I should have to reclone them, do the changes from your email on them, and send them back to you that way? And if so, when do I move them back to my Documents -> GitHub?

Or is this error something different?

From: Anne Gentle <notifications@github.com>
Reply-To: CiscoDevNet/fmc-rest-api <reply@reply.github.com>
Date: Friday, June 22, 2018 at 3:32 PM
To: CiscoDevNet/fmc-rest-api <fmc-rest-api@noreply.github.com>
Cc: "Renee Bornstein -X (rbornste - INSIGHT GLOBAL INC at Cisco)" <rbornste@cisco.com>, Author <author@noreply.github.com>
Subject: Re: [CiscoDevNet/fmc-rest-api] CLUS-firepower-restapi112-md1 (#46)


@annegentle requested changes on this pull request.

You could also delete the extra /posts/files/lab-id image references here if you want.

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197583893>:

>



-## Learning Objective

-After completing this module you will have a basic understanding of FMC REST APIs CRUD operations

+## Learning objective

You can delete "Learning objective" heading.

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197583993>:

>



 ## Read operation GET

-If you are using DevNet sandbox  https://fmcrestapisandbox.cisco.com/api/api-explorer/

-

-For the CLUS 17 workshop session the username and password is provided to you. These credentials are only valid for the CLUS17 session.

+If you are using the [DevNet Sandbox] (https://fmcrestapisandbox.cisco.com/api/api-explorer/), for this workshop session the username and password is provided to you. These credentials are only valid for this session.

Having a space after the square bracket ] means the link will not render correctly. I wonder also why this link is the fmcrestapisandbox, but in the prior PR the link was https://cisco-tid.cisco.com/api/api-explorer/?

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197584043>:

>  ## Write operation POST



-This time you need to click on the POST operation and Click Examples to get JSON

+This time you need to click on the POST operation, and Click Examples to get JSON.

Click Examples probably doesn't need to be capitalized.

________________________________

In labs/firepower-restapi-112/1.md<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#discussion_r197584062>:

> @@ -67,7 +68,8 @@ Alternatively, You can copy JSON from here.

 ```





-Copy and paste the JSON in the API CONSOLE *Body* section and Click POST

+

+Copy and paste the JSON in the API CONSOLE *Body* section, and Click POST.

Click does not need to be capitalized here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CiscoDevNet/fmc-rest-api/pull/46#pullrequestreview-131364385>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlQdkKa94RZieP8tnD6UbQtSHLoIhe2uks5t_XB8gaJpZM4UVnHP>.

2018-06-28 14:54 UTC, ReneeBornstein commented
Made the changes in Atom.

2018-07-10 21:57 UTC, annegentle approved these changes

2018-07-10 21:57 UTC, merged