Revisions to FMC 102 (Authentication tokens)
CiscoDevNet/fmc-rest-api pull request #62
Opened 2019-01-16 22:21 UTC by klevenstein

* General edits
* Expanding the Postman procedures with more detail
* Restructing of lab into 3 parts
* Retitling to remove "102"

2019-01-16 22:22 UTC, klevenstein commented
There's still one section that's incomplete; am getting more info to contextualize the Python script in 3.md.

2019-01-17 20:48 UTC, annegentle requested changes
This is a nice re-write! Minor comments sprinkled within.

2019-01-17 20:48 UTC, annegentle commented on labs/firepower-restapi-102/2.md
I think it's documented in the prior lab for FMC itself.

2019-01-17 20:48 UTC, annegentle commented on labs/firepower-restapi-102/3.md
> +The following Python script defines
missing rest of sentence.

2019-01-17 20:48 UTC, annegentle commented on labs/firepower-restapi-102/firepower-restapi-102.json
> +        "title": "# Firepower Management Center (FMC) REST API authentication tokens",
You can remove the # mark.

2019-01-23 22:27 UTC, merged